# Step 1: Preprocessing the Data

In [5]:
from google.colab import files
uploaded = files.upload()

Saving charity_data.csv to charity_data (2).csv

In [7]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [8]:
# TARGET VARIABLE : "IS_SUCCESSFUL"
# FEATURES : "INCOME_AMT" AND "ASK_AMT"

In [9]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN','NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [10]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [11]:
# Look at APPLICATION_TYPE value counts for binning
app_bins = application_df['APPLICATION_TYPE'].value_counts()
app_bins

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [12]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = app_bins.loc[app_bins<500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [13]:
# Look at CLASSIFICATION value counts for binning
class_bins = application_df['CLASSIFICATION'].value_counts()
class_bins

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [14]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_bins.loc[class_bins>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [15]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = class_bins.loc[class_bins<100].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [16]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [17]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=["IS_SUCCESSFUL"],axis=1)
y = application_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=39)

In [18]:
X

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [19]:
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [20]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(25724, 49)
(8575, 49)

# Step 2: Compile, Train and Evaluate the Model

# model 1:

In [22]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=9, input_dim=len(X_train.columns), activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=25, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 450

 dense_1 (Dense)             (None, 25)                250

 dense_2 (Dense)             (None, 1)                 26

=================================================================
Total params: 726
Trainable params: 726
Non-trainable params: 0
_________________________________________________________________

In [23]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5932 - accuracy: 0.7016
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7266
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7274
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7281
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7285
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7299
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7302
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7314
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7312
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7314
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7324
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7327
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7322
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7327
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7322
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7332
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7322
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7327
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7329
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7335
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7326
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7346
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7341
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7339
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7345
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7335
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7346
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7353
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7327
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7342
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7342
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7337
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7336
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7350
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7352
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7339
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7352
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7349
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7356
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7352
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7351
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7358
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7347
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7358
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7349
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7351
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7358
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7357
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7358
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7355
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7355
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7357
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7363
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7366
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7352
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7363
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7356
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7368
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7354
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7358
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7367
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7366
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7354
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7369
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7362
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7364
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7361
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7361
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7370
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7361
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7361
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7349
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7376
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7378
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7355
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7363
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7360
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7369
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7364
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7361
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7353
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7364
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7365
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7371
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7365
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7371
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7368
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7372
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7376
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7353
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7383
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7374
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7367
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7372
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7370
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7369
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7365

In [25]:
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test,verbose=2)
print(f"Loss; {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5546 - accuracy: 0.7240 - 463ms/epoch - 2ms/step
Loss; 0.5546121597290039, Accuracy: 0.7239649891853333

In [26]:
# Export model to HDF5 file
from google.colab import files

nn.save("AlphabetSoupCharity.h5")
files.download("AlphabetSoupCharity.h5")